export const V2_ROUTES = {
  home: "/v2",
  capitulos: "/v2/capitulos",
  personajes: "/v2/personajes",
  facciones: "/v2/facciones",
  lugares: "/v2/lugares",
  mapa: "/v2/mapa",
  dioses: "/v2/dioses",
  objetos: "/v2/objetos",
  misterios: "/v2/misterios",
  mundo: "/v2/mundo",
  buscar: "/v2/buscar",
} as const;

export const LEGACY_PUBLIC_REDIRECTS: Record<string, string> = {
  "/": V2_ROUTES.home,
  "/buscar": V2_ROUTES.buscar,
  "/cronicas": V2_ROUTES.capitulos,
  "/cronicas/:num": `${V2_ROUTES.capitulos}/:num`,
  "/personajes": V2_ROUTES.personajes,
  "/personajes/:slug": `${V2_ROUTES.personajes}/:slug`,
  "/facciones": V2_ROUTES.facciones,
  "/facciones/:slug": `${V2_ROUTES.facciones}/:slug`,
  "/lugares": V2_ROUTES.lugares,
  "/lugares/:slug": `${V2_ROUTES.lugares}/:slug`,
  "/mapa": V2_ROUTES.mapa,
  "/objetos": V2_ROUTES.objetos,
  "/objetos/:slug": `${V2_ROUTES.objetos}/:slug`,
  "/misterios": V2_ROUTES.misterios,
  "/misterios/:slug": `${V2_ROUTES.misterios}/:slug`,
  "/worldbuilding": V2_ROUTES.mundo,
  "/worldbuilding/:slug": `${V2_ROUTES.mundo}/:slug`,
  "/v2/archivos": V2_ROUTES.objetos,
  "/episodios": V2_ROUTES.capitulos,
  "/episodios/:num": `${V2_ROUTES.capitulos}/:num`,
  "/entidades/personaje": V2_ROUTES.personajes,
  "/entidades/personaje/:slug": `${V2_ROUTES.personajes}/:slug`,
  "/entidades/lugar": V2_ROUTES.lugares,
  "/entidades/lugar/:slug": `${V2_ROUTES.lugares}/:slug`,
  "/entidades/faccion": V2_ROUTES.facciones,
  "/entidades/faccion/:slug": `${V2_ROUTES.facciones}/:slug`,
  "/entidades/objeto": V2_ROUTES.objetos,
  "/entidades/objeto/:slug": `${V2_ROUTES.objetos}/:slug`,
  "/entidades/misterio": V2_ROUTES.misterios,
  "/entidades/misterio/:slug": `${V2_ROUTES.misterios}/:slug`,
  "/entidades/worldbuilding": V2_ROUTES.mundo,
  "/entidades/worldbuilding/:slug": `${V2_ROUTES.mundo}/:slug`,
  "/entidades/evento": V2_ROUTES.capitulos,
  "/entidades/evento/:slug": V2_ROUTES.capitulos,
  "/entidades/quote": V2_ROUTES.capitulos,
  "/entidades/quote/:slug": V2_ROUTES.capitulos,
  "/entidades/decision": V2_ROUTES.capitulos,
  "/entidades/decision/:slug": V2_ROUTES.capitulos,
};

export function isV2PublicHref(href: string): boolean {
  if (!href.startsWith("/")) return false;
  const path = href.split(/[?#]/, 1)[0];
  return path === V2_ROUTES.home || path.startsWith(`${V2_ROUTES.home}/`);
}
